### ISSUE TITLE
Error on installation 

### ISSUE THREAD

**Issue by zersorger** [yunndlalala/dynamic_earthquake_triggering#6]
Hey, when I want to install it by pip install dytrypy I get the following error. Any idea how to fix it?

` error: Command "gcc -pthread -B /home/henning/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-build-env-iwmm3e7v/overlay/lib/python3.8/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.8/numpy/distutils/include -I/home/henning/anaconda3/include/python3.8 -c obspy/io/gse2/src/GSE_UTI/gse_functions.c -o build/temp.linux-x86_64-3.8/obspy/io/gse2/src/GSE_UTI/gse_functions.o -MMD -MF build/temp.linux-x86_64-3.8/obspy/io/gse2/src/GSE_UTI/gse_functions.o.d" failed with exit status 127
  ----------------------------------------
  ERROR: Failed building wheel for obspy
Failed to build obspy
ERROR: Could not build wheels for obspy which use PEP 517 and cannot be installed directly
`

Best wishes

**Comment by yunndlalala** [comment]
sorry for this very very very late response ⊙﹏⊙. Hope that you have fixed this problem. I have never got this error, however, I think it is possible due to the installation of obspy. so, you can try installing the obspy additionally if there is no error for the other parts. Or, installing obspy first.
